export default {
    appName: 'tcc-app',

    signIn: 'Acessar',
    signInFacebook: 'Entrar com Facebook',
    signInGoogle: 'Entrar com Google',
    password: 'Senha',
    login: 'Login',
    welcome: 'Bem Vindo',
    newHere: 'Novo por aqui?',
    signUp: 'Cadastre-se',
    alreadyRegistered: 'Já é cadastrado?',
    confirmPassword: 'Confirmar Senha',

    opportunities: 'Oportunidades',
    feed: 'Feed',
    profile: 'Perfil',

    hello: 'Olá, ',
    howDoYouWannaHelp: 'Quais causas você quer ajudar?',

    interests: 'Interesses',
    animals: 'Animais',
    humanRights: 'Direitos Humanos',
    sports: 'Esportes',
    environment: 'Meio Ambiente',
    health: 'Saúde',
    education: 'Educação',
    arts: 'Artes',
    others: 'Outros',

    confirm: 'Confirmar',
    error: 'Erro',
    errorConfirm: 'Falha ao Confirmar',
    mustSelectAtLeastOne: 'Você precisa selecionar ao menos um para continuar.',
    somethinWentWrong: 'Algo deu errado, tente novamente mais tarde.',

    seeDetails: 'Ver Detalhes',

    languages: 'Idiomas',
    formation: 'Formação',

    editProfile: 'Editar Perfil',
    disconnect: 'Desconectar',

    register: 'Me inscrever',
    unRegister: 'Cancelar Cadastro',
    requirements: 'Requisitos',
    address: 'Endereço',
    periodAndDuration: 'Período e Duração',
    socialProject: 'Projeto Social',
    socialProjInfo:
        'Informações sobre a ONG, instituição ou projeto social que disponibilizou a vaga.',
    knowMore: 'Saiba Mais',

    presentationLetter: 'Carta de Apresentação',
    typeSomething: 'Digite algo...',
    cancel: 'Cancelar',
    congratulations: 'Parabéns',
    registered: 'Você acaba de se registrar para essa vaga.',
    ok: 'Ok',

    contact: 'Contato',

    personalData: 'Dados Pessoais',
    editPhoto: 'Editar Foto',
    nameHint: 'Nome social ou de registro',
    gender: 'Gênero',
    genderHint: 'Gênero com qual se identifica',
    nationality: 'Nacionalidade',
    bornDay: 'Data de nascimento',
    presentation: 'Breve Apresentação',
    institution: 'Universidade',
    course: 'Curso',
    name: 'Nome',
    email: 'Email',
    save: 'Salvar',
    back: 'Voltar',

    mustNotBeEmpty: 'O campo precisa ser preenchido',
    passwordsMustMatch: 'As senhas precisam coincidir',
    somethingWentWrong: 'Algo de errado aconteceu',
    invalidEmail: 'Email inválido',
    emailAlreadyUsed: 'Email já está em uso',
    weakPassword: 'Senha muito fraca',
    tooManyTries: 'Muitas tentativas foram feitas, tente novamente mais tarde',
    wrongEmailOrPassword: 'Email ou senha inválidos',
    verifyEmail: 'Email não verificado',
};
